name: Pull Request Lint, Typecheck, & Build

on:
  pull_request:
    branches: ['main']

jobs:
  lint-typecheck-and-build:
    depends-on: version-tag-create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 18.18.x
          cache: npm

      - name: Lint, Typecheck & Build Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # lint, typecheck and build the app before running electron-builder
          build_script_name: prebuild
        env:
          # https://www.electron.build/code-signing#how-to-disable-code-signing-during-the-build-process-on-macos
          CSC_IDENTITY_AUTO_DISCOVERY: false