name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: Release Type
        type: choice
        required: true
        default: official
        options:
          - official
          - alpha
          - beta
          - rc
      draft:
        description: Draft
        type: boolean
        required: true
        default: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Ensure release is only run on main
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # Grab all the git history for building changelog
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.14.x
          cache: npm

      - name: NPM Install
        run: npm install

      - name: Update Official Version
        if: ${{ inputs.releaseType == 'official' }}
        run: npm run version

      - name: Update Prerelease Version
        if: ${{ inputs.releaseType != 'official' }}
        run: npm run version -- --prerelease ${{ inputs.releaseType }}

      - name: Get Version
        id: get-version
        run: echo "::set-output name=version::$(node --print "'v'.concat(require('./package.json').version)")"

      - name: Commit Version
        id: commit-version
        uses: EndBug/add-and-commit@v9
        with:
          message: ${{ format('release {0}', steps.get-version.outputs.version) }}
          pathspec_error_handling: exitImmediately
          tag: ${{ steps.get-version.outputs.version }}

      - name: Exit on Commit, Push, Tag, Tag Push Failure
        if: ${{ steps.commit-version.outputs.committed != 'true' || steps.commit-version.outputs.pushed != 'true' || steps.commit-version.outputs.tagged != 'true' || steps.commit-version.outputs.tag_pushed != 'true'}}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Commit failed')

      # See https://www.electron.build/multi-platform-build#docker
      - name: Lint, Typecheck, and Build in Electron Builder Container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: 'docker run --rm --env-file <(env | grep -iE "DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_") --env ELECTRON_CACHE="/root/.cache/electron" --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.cache/electron:/root/.cache/electron -v ~/.cache/electron-builder:/root/.cache/electron-builder electronuserland/builder:16-wine /bin/bash -c "yarn install && yarn run build"'

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "releases/*.exe, releases/*.exe.blockmap, releases/latest.yml, releases/*.AppImage, releases/latest-linux.yml"
          bodyFile: "RELEASE-NOTES.md"
          draft: ${{ inputs.draft }}
          name: ${{ steps.get-version.outputs.version }}
          prerelease: ${{ inputs.releaseType != 'official' }}
          tag: ${{ steps.get-version.outputs.version }}